update version

diff --git a/proxy/aa b/proxy/aa
--- a/proxy/aa
+++ b/proxy/aa
@@ -1,42 +1,67 @@
 #!/bin/sh
-NAME="proxy"
-EXEC="sh"
 
-## check docker running.
-if ! docker info >/dev/null 2>&1; then
-    echo "Docker does not seem to be running, exiting..."
-    exit 1
+# Get the current working directory
+PWD="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+
+# Copy env.example or .env.example to .env if .env does not exist
+if [ ! -f "$PWD/.env" ]; then
+    if [ -f "$PWD/env.example" ]; then
+        cp "$PWD/env.example" "$PWD/.env" 2>/dev/null
+    elif [ -f "$PWD/.env.example" ]; then
+        cp "$PWD/.env.example" "$PWD/.env" 2>/dev/null
+    fi
 fi
 
-## init scripts.
-[ "$1" = "init" ] && {
-    echo 'init start services.'
+# Load the .env file if it exists
+[ -f "$PWD/.env" ] && . "$PWD/.env"
 
-    mkdir -p work/.init/
+# Set the name and default exec command
+NAME=${POD_NAME:-$(basename "$PWD")}
+EXEC=${EXEC_COMMAND:-"sh"}
 
-    cat <<EOF >work/.init/init.sh
-#!/bin/sh
-sctl enable ss
-sctl enable v2ray
-sctl enable wireguard
-EOF
-
+# Action functions
+action_docker() {
+    wget a.zzci.cc/tpl/docker-compose.yml
 }
 
-[ "$1" = "rm" ] && {
+action_build() {
+    docker build --rm -t "$NAME" .
+}
+
+action_rm() {
     docker compose down
 }
 
-[ "$1" = "e" ] && {
-    if [ "$2" != "" ]; then
-        EXEC=$2
-    fi
-    docker exec -ti $NAME $EXEC
+action_restart() {
+    docker compose restart
 }
 
-[ "$1" = "run" ] && {
+action_exec() {
+    [ -n "$1" ] && EXEC="$1"
+    docker compose exec -ti app "$EXEC"
+}
+
+action_run() {
     docker compose down
     docker compose up -d
 }
 
-exit 0
+# Set the default action to "build" if none is provided
+action=${1:-run}
+if [ "$#" -gt 1 ]; then
+  shift
+fi
+
+# Function to check if a function exists
+function_exists() {
+    type "$1" >/dev/null 2>&1
+}
+
+# Call the action function if it exists, otherwise show an error
+if function_exists "action_$action"; then
+    "action_$action" "$@"
+else
+    echo "Error: Unknown action: '$action'"
+    echo "Usage: $0 <action> <args>"
+    exit 1
+fi
